use once_cell::sync::Lazy;

pub static STATES: Lazy<Vec<&str>> = Lazy::new(|| {
    vec![
        "alabama",
        "alaska",
        "american samoa",
        "arizona",
        "arkansas",
        "california",
        "colorado",
        "connecticut",
        "delaware",
        "district of columbia",
        "federated states of micronesia",
        "florida",
        "georgia",
        "guam",
        "hawaii",
        "idaho",
        "illinois",
        "indiana",
        "iowa",
        "kansas",
        "kentucky",
        "louisiana",
        "maine",
        "marshall islands",
        "maryland",
        "massachusetts",
        "michigan",
        "minnesota",
        "mississippi",
        "missouri",
        "montana",
        "nebraska",
        "nevada",
        "new hampshire",
        "new jersey",
        "new mexico",
        "new york",
        "north carolina",
        "north dakota",
        "northern mariana islands",
        "ohio",
        "oklahoma",
        "oregon",
        "palau",
        "pennsylvania",
        "puerto rico",
        "rhode island",
        "south carolina",
        "south dakota",
        "tennessee",
        "texas",
        "utah",
        "vermont",
        "virgin islands",
        "virginia",
        "washington",
        "west virginia",
        "wisconsin",
        "wyoming",
    ]
});

pub static STATES_ABBVR: Lazy<Vec<&str>> = Lazy::new(|| {
    vec![
        // "alabama", 
        "AL",
        // "alaska", 
        "AK",
        // "american samoa", 
        "AS",
        // "arizona", 
        "AZ",
        // "arkansas", 
        "AR",
        // "california", 
        "CA",
        // "colorado", 
        "CO",
        // "connecticut", 
        "CT",
        // "delaware", 
        "DE",
        // "district of columbia", 
        "DC",
        // "federated states of micronesia", 
        "FM",
        // "florida", 
        "FL",
        // "georgia", 
        "GA",
        // "guam", 
        "GU",
        // "hawaii", 
        "HI",
        // "idaho", 
        "ID",
        // "illinois", 
        "IL",
        // "indiana", 
        "IN",
        // "iowa", 
        "IA",
        // "kansas", 
        "KS",
        // "kentucky", 
        "KY",
        // "louisiana", 
        "LA",
        // "maine", 
        "ME",
        // "marshall islands", 
        "MH",
        // "maryland", 
        "MD",
        // "massachusetts", 
        "MA",
        // "michigan", 
        "MI",
        // "minnesota", 
        "MN",
        // "mississippi", 
        "MS",
        // "missouri", 
        "MO",
        // "montana", 
        "MT",
        // "nebraska", 
        "NE",
        // "nevada", 
        "NV",
        // "new hampshire", 
        "NH",
        // "new jersey", 
        "NJ",
        // "new mexico", 
        "NM",
        // "new york", 
        "NY",
        // "north carolina", 
        "NC",
        // "north dakota", 
        "ND",
        // "northern mariana islands", 
        "MP",
        // "ohio", 
        "OH",
        // "oklahoma", 
        "OK",
        // "oregon", 
        "OR",
        // "palau", 
        "PW",
        // "pennsylvania", 
        "PA",
        // "puerto rico", 
        "PR",
        // "rhode island", 
        "RI",
        // "south carolina", 
        "SC",
        // "south dakota", 
        "SD",
        // "tennessee", 
        "TN",
        // "texas", 
        "TX",
        // "utah", 
        "UT",
        // "vermont", 
        "VT",
        // "virgin islands", 
        "VI",
        // "virginia", 
        "VA",
        // "washington", 
        "WA",
        // "west virginia", 
        "WV",
        // "wisconsin", 
        "WI",
        // "wyoming", 
        "WY",
    ]
});
